name: Testing
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  test:
    name: Unit tests
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 11.3
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Testing iOS app
        run: xcodebuild -project calcul8.xcodeproj -scheme calcul8 -destination platform=iOS\ Simulator,OS=15.0,name=iPad\ Pro\ \(11\-inch\)\ \(3rd\ generation\) clean test
